spring:
  application:
    name: product-service


  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
